### ISSUE TITLE
Create Round class

### ISSUE THREAD

**Issue by libbyeh** [kaohman/jeopardy#3]
Include: 

Properties:
- [x] roundNum
- [x] dailyDoubleClue
- [x] categories
- [x] clues

Methods:
- [ ] change round
- [ ] change player during round
- [x] validate answer
- [x] pull clue
- [x] declare winner

**Comment by kaohman** [comment]
Created class properties and methods. I added an additional method to Round called getCategoryNames that takes an array of categoryIds, finds the associate names for each, converts the names from camelCase, and stores these names in an array in the class. These are the names that will be used on the DOM. I think the change round and change player methods might be better to include on the Game class?
